Week_5/Week_5_Tue/members-2/config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "static_pages#home"
get "/secret_page", to:"static_pages#secret_page"
get "/login", to: "sessions#new"
post "/login", to: "sessions#create"
delete "/logout", to: "sessions#destroy"

  resources "users"
end

Week_5/Week_5_Tue/members-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Week_5/Week_5_Tue/members-2/app/models/user.rb
class User < ApplicationRecord
	
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

Week_5/Week_5_Tue/members-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
include SessionsHelper
end

Week_5/Week_5_Tue/members-2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	  def new
	  end

		def create
		  	user = User.find_by(email: params_session[:email].downcase)
		  	if user && user.authenticate(params_session[:password])
		  		log_in user
		  		redirect_to root_path
		  	else 
		  		flash.now[:danger] = 'Invalid email/password combination'
		  		render 'new'
		  	end 
		end

		def destroy
			session.delete(:user_id)
			redirect_to '/login'
		end

	private
		def params_session
			params.require(:session).permit(:email, :password)
		end
end

Week_5/Week_5_Tue/members-2/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def secret_page
		if !logged_in?
			flash[:danger] = 'Loggue toi pour accéder à la page'
			redirect_to root_path
		end
	end 
end

Week_5/Week_5_Tue/members-2/app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
		log_in @user
		redirect_to root_path
	else
		render 'new'
	end
end
	
	def edit
		@user = User.find(params[:id])
		if user != current_user
			flash[:danger] = 'You cannot edit someone else'
			redirect_to users_path
		end
	end

	def update
		@user = User.find(params[:id])
    		if @user.update(user_params)
      		redirect_to users_path
    		else
      		render 'Edit'
    		end
    end

private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

Week_5/Week_5_Tue/members-2/app/helpers/application_helper.rb
module ApplicationHelper
end

Week_5/Week_5_Tue/members-2/app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in (user)
		session[:user_id] = user.id
	end

	def current_user
	@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
	!current_user.nil?
	end
end 

Week_5/Week_5_Tue/members-2/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Week_5/Week_5_Tue/members-2/app/helpers/users_helper.rb
module UsersHelper
end

Week_5/Week_5_Tue/members-2/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/">Hello</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Index<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/users">Users</a>
          </li>
        </ul>
      </div>
    </nav>

Week_5/Week_5_Tue/members-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
 </head>

	<body>
		<%= render "layouts/header" %>
   <div class="container" style="padding-top: 5rem;">
    
		<%= yield %>
	</body>
</html>

Week_5/Week_5_Tue/members-2/app/views/static_pages/home.html.erb
<h1>Chuuut c'est une page secrète ! Connectez-vous pour y accéder !</h1>

<% if logged_in? %>
	<p><a href='<%= secret_page_path %>'> découvre la page secrète !</a></p>
	<% end %>

Week_5/Week_5_Tue/members-2/app/views/static_pages/secret_page.html.erb
Hello this is a secret 

Week_5/Week_5_Tue/members-2/app/views/users/edit.html.erb
<h1>Welcome</h1>

<%= form_for :user, url: user_path, method: :patch do |f| %>
 Email: <%= f.text_field :email %><br/>
 Mot de passe: <%= f.text_field :password %><br/>
 Confirmation du mot de passe: <%= f.text_field :password_confirmation %><br/>
 <br/>
 <%= f.submit %>
<% end %>

Week_5/Week_5_Tue/members-2/app/views/users/index.html.erb
<table class="table">
 <thead class="thead-light">
   <tr>
     <th>id</th>
     <th>email</th>
   </tr>
 </thead>
 <tbody>
   <% @users.each do |user| %>
     <tr>
       <td><%= link_to user.id, edit_user_path(user) %></td>
       <td><%= user.email %></td>
     </tr>
   <% end %>
 </tbody>
</table>

<%= button_to 'new!', new_user_path, method: :get, class: "btn btn-default" %>

Week_5/Week_5_Tue/members-2/app/views/users/new.html.erb
<h1>Welcome!</h1>

<%= form_for @user do |f| %>
 Email: <%= f.text_field :email %><br/>
 Mot de passe: <%= f.text_field :password %><br/>
 Confirmation du mot de passe: <%= f.text_field :password_confirmation %><br/>
 <br/>
 <%= f.submit %>
<% end %>