Week_4/Week_4_Wed/the-gossip-project/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'gossips#index'

resources :gossips

get 'gossips/index'

end

Week_4/Week_4_Wed/the-gossip-project/app/models/article.rb
class Article < ApplicationRecord
end

Week_4/Week_4_Wed/the-gossip-project/app/models/gossip.rb
class Gossip < ApplicationRecord
end

Week_4/Week_4_Wed/the-gossip-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Week_4/Week_4_Wed/the-gossip-project/app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def new
		@gossip = Gossip.new
	end

	def create
		@gossip = Gossip.new(gossip_params)
  	 	@gossip.save
  		redirect_to @gossip
	end

	def index
		@gossips = Gossip.all
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])
    	@gossip.anonymoous_author = gossip_params[:anonymoous_author]
    	@gossip.content = gossip_params[:content]
    		if @gossip.update(gossip_params)
      		redirect_to @gossip
    		else
      		render 'Modifier'
    end
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end

private
	def gossip_params
		params[:gossip].permit(:anonymoous_author, :content)
	end


end

Week_4/Week_4_Wed/the-gossip-project/app/helpers/gossips_helper.rb
module GossipsHelper
end

Week_4/Week_4_Wed/the-gossip-project/app/views/gossips/edit.html.erb
<h1>Modifier le gossip</h1>
 
<%= form_for(:gossip, url: gossip_path, method: :patch) do |f| %>
  Auteur : <%= f.text_field :anonymoous_author %><br />
  Contenu : <%= f.text_area :content %><br />
  <%= f.submit %>
<% end %>

<%= link_to 'Supprimer le gossip', @gossip, method: :delete %>
<%= link_to 'Retour', root_path %>



<!-- Autre méthode
<%= form_with(model: @gossip, local: true) do |form| %>
 
  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gossip.errors.count, "error") %> on ne peut sauvegarder ce gossip:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :auteur %><br>
    <%= form.text_field :anonymoous_author %>
  </p>
 
  <p>
    <%= form.label :contenu %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Supprimer le gossip', @gossip, method: :delete %>
<%= link_to 'Retour', gossips_path %>

Week_4/Week_4_Wed/the-gossip-project/app/views/gossips/index.html.erb
<h1> Liste des gossips </h1>
<table>
  <tr>
    <th>Auteur</th>
    <th>Contenu</th>
  </tr>
 
  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.anonymoous_author%></td>
      <td><%= link_to gossip.content, gossip_path(gossip)%></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Ajouter un gossip', new_gossip_path %>

Week_4/Week_4_Wed/the-gossip-project/app/views/gossips/new.html.erb
<%= form_for(:gossip, url: '/gossips') do |f| %>
  auteur: <%= f.text_field :anonymoous_author %><br />
  contenu: <%= f.text_field :content %><br />
  <%= f.submit %>
<% end %>

Week_4/Week_4_Wed/the-gossip-project/app/views/gossips/show.html.erb
Le gossip que vous avez sélectionné : <br>
<%= @gossip.anonymoous_author %> dit
<%= @gossip.content %>

<br>
<br>
<%= link_to 'Modifier le gossip', edit_gossip_path %>
<%= link_to 'Afficher les gossips', gossips_path %>

Week_4/Week_4_Wed/the-gossip-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.1.1.min.css"/>
  </head>

  <body>
    <%= yield %>
  </body>
</html>